---
downloads: ~/.ansible-downloads/

configure_sudoers: yes
configure_terminal: yes
configure_macos: yes

dotfiles_repo: https://gitlab.com/jkennemer/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Projects/dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bash_prompt
  - .bashrc
  - .curlrc
  - .editorconfig
  - .exports
  - .functions
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .inputrc
  - .macos
  - .screenrc
  - .tmux.conf
  - .vimrc
  - .wgetrc
  - .zshrc
  - Brewfile

homebrew_installed_packages:
  # - ansible # Installed via Pip.


homebrew_taps:
  - homebrew/core
  - homebrew/bundle


homebrew_cask_appdir: /Applications
homebrew_cask_apps:


# See `tobymccann.mas` role documentation for usage instructions.
mas_installed_app_ids: []
mas_email: ""
mas_password: ""
